---
- name: install yq
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    dest: /usr/bin/yq
    owner: root
    group: root
    mode: o=rwx,g=rx,o=rx
