---
- name: install yq
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_{{ yq_arch }}"
    dest: /usr/bin/yq
    owner: root
    group: root
    mode: o=rwx,g=rx,o=rx
