- name: Install postgres pre process
  hosts: all
  gather_facts: false
  become: true
  vars:
    postgres_uid: "3000"
  tasks:
    - name: Check required account
      ansible.builtin.shell: |
        id postgres
      register: result
      failed_when: result.rc not in [0, 1]

    - name: Create the account
      ansible.builtin.user:
        name: "postgres"
        uid: "{{ postgres_uid }}"
        password: "postgres | password_hash('sha512')"
        shell: "/bin/bash"
      when: result.rc == 1

    - name: Install dependency
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - gnupg
          - lsb-release

    - name: Remove existing software
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
        autoremove: true
        state: absent
