- name: install wget post process
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: set proxy
      shell: |
        type wget >/dev/null 2>&1

        if ! cat '/etc/wgetrc' | grep -q '^http_proxy'; then
          echo 'http_proxy = http://{{ proxy_setting }}'  >> '/etc/wgetrc'
        fi
        if ! cat '/etc/wgetrc' | grep -q '^https_proxy'; then
          echo 'https_proxy = http://{{ proxy_setting }}' >> '/etc/wgetrc'
        fi
      when: proxy_setting != ""
