- name: Install postgres post process
  hosts: all
  gather_facts: false
  become: true
  become_user: postgres
  vars:
    bin_dir: "/usr/lib/postgresql/14/bin"
    db_dir: "/var/lib/postgresql/data"
    localhost_ip: "127.0.0.1/32"
    localnet_ip: "172.18.0.0/16"
  tasks:
    - name: Init db
      ansible.builtin.shell: |
        {{ bin_dir }}/initdb "{{ db_dir }}"

    - name: Enable listen
      ansible.builtin.blockinfile:
        path: "{{ db_dir }}/postgresql.conf"
        block: |
          listen_addresses = '*'
          port = 5432

    - name: Enable connection
      ansible.builtin.blockinfile:
        path: "{{ db_dir }}/pg_hba.conf"
        block: |
          host all all {{ localhost_ip }} trust
          host all all {{ localnet_ip }} trust

    - name: Start service
      ansible.builtin.shell: |
        {{ bin_dir }}/pg_ctl -D "{{ db_dir }}" -w -t 60 start
