- name: Install docker main process
  hosts: all
  gather_facts: false
  become: true
  environment:
    http_proxy: "{{ proxy_setting }}"
    https_proxy: "{{ proxy_setting }}"
  vars:
    gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    gpg_path: "/etc/apt/keyrings/docker.gpg"
    download_url: "https://download.docker.com/linux/ubuntu"
    list_path: "/etc/apt/sources.list.d/docker.list"
    docker_ver: "5:25.0.5-1~ubuntu.22.04~jammy"
  tasks:
    - name: Make temp file
      ansible.builtin.tempfile:
      register: temp_gpg

    - name: Download temp gpg
      ansible.builtin.get_url:
        url: "{{ gpg_url }}"
        dest: "{{ temp_gpg.path }}"
        force: true
        owner: root
        group: root
        mode: "0644"
        use_proxy: "{{ proxy_setting != '' }}"

    - name: Prepare gpg directory
      ansible.builtin.file:
        path: "{{ gpg_path | dirname }}"
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Delete old gpg (cannot skip this)
      ansible.builtin.file:
        path: "{{ gpg_path }}"
        state: absent

    - name: Register external repository
      ansible.builtin.shell: |
        gpg --dearmor -o "{{ gpg_path }}" "{{ temp_gpg.path }}"
        printf 'deb [arch=%s signed-by=%s] %s %s stable\n' \
          "$(dpkg --print-architecture)" "{{ gpg_path }}"  \
          "{{ download_url }}" "$(lsb_release -cs)"        \
          >"{{ list_path }}"

    - name: Delete temp gpg
      ansible.builtin.file:
        path: "{{ temp_gpg.path }}"
        state: absent

    - name: Install the specific version
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce-cli={{ docker_ver }}
          - docker-ce={{ docker_ver }}

    - name: Hold the ce-cli
      ansible.builtin.dpkg_selections:
        name: docker-ce-cli
        selection: hold

    - name: Hold the ce
      ansible.builtin.dpkg_selections:
        name: docker-ce
        selection: hold
