- name: install postgres post process
  hosts: all
  gather_facts: no
  become: yes
  become_user: postgres
  vars:
    BIN_DIR: "/usr/lib/postgresql/14/bin"
    DB_DIR:  "/var/lib/postgresql/data"
    LOCALHOST_IP: "127.0.0.1/32"
    LOCALNET_IP:  "172.18.0.0/16"
  tasks:
    - name: init db
      ansible.builtin.shell: |
        {{ BIN_DIR }}/initdb "{{ DB_DIR }}"

    - name: enable listen
      ansible.builtin.blockinfile:
        path: "{{ DB_DIR }}/postgresql.conf"
        block: |
          listen_addresses = '*'
          port = 5432

    - name: enable connection
      ansible.builtin.blockinfile:
        path: "{{ DB_DIR }}/pg_hba.conf"
        block: |
          host all all {{ LOCALHOST_IP }} trust
          host all all {{ LOCALNET_IP }} trust

    - name: start service
      ansible.builtin.shell: |
        {{ BIN_DIR }}/pg_ctl -D "{{ DB_DIR }}" -w -t 60 start
