- name: Install yq main process
  hosts: all
  gather_facts: true
  become: true
  environment:
    http_proxy: "{{ proxy_setting }}"
    https_proxy: "{{ proxy_setting }}"
  vars:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  tasks:
    - name: Install yq
      ansible.builtin.get_url:
        url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_{{ arch }}"
        dest: "/usr/local/bin/yq"
        owner: root
        group: root
        mode: "0755"
        use_proxy: "{{ proxy_setting != '' }}"
