- name: install docker post process
  hosts: all
  gather_facts: no
  become: yes
  tasks:
     - name: set proxy
       shell: |
         if type docker >/dev/null 2>&1; then
           {
             echo '[service]'
             echo 'Environment="HTTP_PROXY=http://{{ proxy_setting }}"'
             echo 'Environment="HTTPS_PROXY=http://{{ proxy_setting }}"'
           } > '/etc/systemd/system/docker.sevice.d/http-proxy.conf'

           systemctl daemon-reload
           systemctl restart docker
         fi
       when: proxy_setting != ""
