- name: install docker main process
  hosts: all
  gather_facts: no
  become: yes
  environment:
    http_proxy:  "{{ proxy_setting }}"
    https_proxy: "{{ proxy_setting }}"
  vars:
    gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    gpg_path: "/etc/apt/keyrings/docker.gpg"
    download_url: "https://download.docker.com/linux/ubuntu"
    list_path: "/etc/apt/sources.list.d/docker.list"
    docker_ver: "5:25.0.5-1~ubuntu.22.04~jammy"
  tasks:
    - name: gather date and time
      setup:
        gather_subset:
          - "date_time"
      when: ansible_date_time is not defined

    - name: set variable
      ansible.builtin.set_fact:
        tmp_path: "/tmp/tmp_gpg_{{ ansible_date_time.date }}"

    - name: download tmp gpg
      get_url:
        url: "{{ gpg_url  }}"
        dest: "{{ tmp_path }}"
        use_proxy: "{{ 'true' if proxy_setting != '' else 'false' }}"

    - name: register external repository
      shell: |
        mkdir -m 0755 -p $(dirname "{{ gpg_path }}")
        [ -e "{{ gpg_path }}" ] && rm "{{ gpg_path }}"

        cat "{{ tmp_path }}" | gpg --dearmor -o "{{ gpg_path }}"

        printf 'deb [arch=%s signed-by=%s] %s %s stable'   \
          "$(dpkg --print-architecture)" "{{ gpg_path }}"  \
          "{{ download_url }}" "$(lsb_release -cs)"        |
        tee "{{ list_path }}" >/dev/null

    - name: delete tmp gpg
      shell: |
        rm "{{ tmp_path }}"

    - name: install the specific version docker
      apt:
        update_cache: yes
        name:
          - docker-ce-cli={{ docker_ver }}
          - docker-ce={{ docker_ver }}

    - name: hold the docker version
      shell: apt-mark hold docker-ce-cli docker-ce
