- name: install docker post process
  hosts: all
  gather_facts: no
  become: yes
  tasks:
     - name: set proxy
       shell: |
         type docker >/dev/null 2>&1

         mkdir -p '/etc/systemd/system/docker.sevice.d'

         {
           echo '[service]'
           echo 'Environment="HTTP_PROXY=http://{{ proxy_setting }}"'
           echo 'Environment="HTTPS_PROXY=http://{{ proxy_setting }}"'
         }                                                            |
         tee '/etc/systemd/system/docker.sevice.d/http-proxy.conf'    |
         cat >/dev/null

         systemctl daemon-reload
         systemctl restart docker
       when: proxy_setting != ""
