- name: install docker main process
  hosts: all
  gather_facts: no
  become: yes
  environment:
    http_proxy:  "{{ proxy_setting }}"
    https_proxy: "{{ proxy_setting }}"
  vars:
    DOCKER_VER: "5:25.0.5-1~ubuntu.22.04~jammy"
  tasks:
    - name: gather date and time
      setup:
        gather_subset:
          - "date_time"
      when: ansible_date_time is not defined

    - name: download tmp docker gpg
      get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: "/tmp/docker_gpg_{{ ansible_date_time.date }}"
        use_proxy: "{{ 'true' if proxy_setting != '' else 'false' }}"

    - name: register external repository
      shell: |
        GPG_PATH='/etc/apt/keyrings/docker.gpg'
        DOCKER_URL='https://download.docker.com/linux/ubuntu'
        LIST_PATH='/etc/apt/sources.list.d/docker.list'
        mkdir -m 0755 -p $(dirname "${GPG_PATH}")
        [ -e "${GPG_PATH}" ] && rm "${GPG_PATH}"

        cat '/tmp/docker_gpg_{{ ansible_date_time.date }}'           |
        gpg --dearmor -o "${GPG_PATH}"

        LIST_LINE=$(printf 'deb [arch=%s signed-by=%s] %s %s stable' \
                 "$(dpkg --print-architecture)" "${GPG_PATH}"        \
                 "${DOCKER_URL}" "$(lsb_release -cs)"                )

        echo "${LIST_LINE}"                                          |
        tee "${LIST_PATH}" >/dev/null

    - name: delete tmp docker gpg
      shell: |
        rm '/tmp/docker_gpg_{{ ansible_date_time.date }}'

    - name: install the specific version docker
      apt:
        update_cache: yes
        name:
          - docker-ce-cli={{ DOCKER_VER }}
          - docker-ce={{ DOCKER_VER }}

    - name: hold the docker version
      shell: apt-mark hold docker-ce-cli docker-ce
