- name: install docker pre process
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: install dependency
      apt:
        name: 
          - ca-certificates
          - gnupg
          - lsb-release

    - name: remove existing software
      apt:
        name:
          - docker-ce-cli
          - docker-ce
        autoremove: yes
        state: absent
